Add -C to customize configure

diff --git a/dobuild b/dobuild
--- a/dobuild
+++ b/dobuild
@@ -87,6 +87,7 @@ SED="/usr/bin/sed"
 # -b [build]
 # -B [build, remove existing copy first]
 # -t [enable tests]
+# -C flags [extra flags to pass to configure]
 # -c cpu [override cpu (sparc or x86)]
 # -o os [override os (illumos or Solaris)]
 # -f feature [enable given patch feature]
@@ -103,6 +104,7 @@ DOBUILD=""
 DOINSTALL=""
 DOCLEAN=""
 JFEATURE=""
+JEXTRACONF=""
 
 #
 # variables
@@ -130,7 +132,7 @@ esac
 dohelp() {
     cat <<EOF
 
-Usage: $0 [-t] [-b | -B | -c cpu | -d | -f feature | -h | -o os | -p | -P] jdk-version
+Usage: $0 [-t] [-b | -B | -c cpu | -C conf_flags | -d | -f feature | -h | -o os | -p | -P] jdk-version
        $0 -i jdk-version|/path/to/jdk
        $0 -e jdk-version
 
@@ -138,18 +140,19 @@ Download, patch, and build a copy of the specified jdk.
 
 Flags:
 
--h show this help
--d just download
--p unpack and patch, download if necessary
--P like -p, remove existing copy and start over
--b build, unpack, patch, and download if necessary
--B like -b, remove existing copy and start over
--t enable and run tests
--c override cpu (sparc or x86)
--o override os (illumos or Solaris)
--f enable given feature
--i link the given jdk into the list of available instances
--e export the given built jdk to a tarball
+-h  show this help
+-d  just download
+-p  unpack and patch, download if necessary
+-P  like -p, remove existing copy and start over
+-b  build, unpack, patch, and download if necessary
+-B  like -b, remove existing copy and start over
+-t  enable and run tests
+-c cpu  override cpu (sparc or x86)
+-o os  override os (illumos or Solaris)
+-C flags  extra flags to pass to configure
+-f feature  enable given patch feature
+-i  link the given jdk into the list of available instances
+-e  export the given built jdk to a tarball
 EOF
 
 exit 1
@@ -158,7 +161,7 @@ exit 1
 #
 # parse any arguments
 #
-while getopts "bBdhpPtiec:o:f:" opt; do
+while getopts "bBdhpPtieC:c:o:f:" opt; do
     case $opt in
 	b)
 	    DOBUILD="yes"
@@ -188,6 +191,9 @@ while getopts "bBdhpPtiec:o:f:" opt; do
 	    ;;
 	e)
 	    DOEXPORT="yes"
+	    ;;
+	C)
+	    JEXTRACONF="$OPTARG"
 	    ;;
 	c)
 	    JARCH="$OPTARG"
@@ -499,6 +505,25 @@ enable_gtest() {
 }
 
 #
+# pass extra flags to configure
+#
+enable_configure_flags() {
+    sfile="$1"
+    extra_flags="$2"
+    if [ ! -f "${sfile}" ]; then
+	echo "ERROR: missing build script $sfile"
+	exit 1
+    fi
+    #
+    # rewrite the build script
+    # there should be a --with-boot-jdk piece, expand that
+    # (if there isn't, we fail in find_boot_jdk, so no need to check here)
+    # need to used gsed for Solaris
+    #
+    ${SED} -i "s:--with-boot-jdk:${extra_flags} --with-boot-jdk:" "${sfile}"
+}
+
+#
 # install a copy of the jdk into the alternate area
 #
 # the argument can be either a tag, like a normal build, or
@@ -795,6 +820,9 @@ else
 	# put in a little marker to say we've actually done this
 	#
 	touch .jdk_sunos_test_enabled
+    fi
+    if [ -n "${JEXTRACONF}" ]; then
+	enable_configure_flags "${JPATCHDIR}/${mver}/${JDKALIAS}/build.sh" "${JEXTRACONF}"
     fi
     find_boot_jdk "${JPATCHDIR}/${mver}/${JDKALIAS}/build.sh"
     echo "Running ${JPATCHDIR}/${mver}/${JDKALIAS}/build.sh"
